### ISSUE TITLE
Page 2 of report is too damn big

### ISSUE THREAD

**Issue by iqbal-lab** [mbhall88/pistis#1]
Is there a way to do this at lower resolution?  It kills Chrome and Adobe Reader, and (oddly) PReview survives but makes a big deal of it and takes tens of seconds. You don't need to plot all of those points for example, you could subsample.

**Comment by mbhall88** [comment]
[Changed the default plot kind to kde](https://github.com/mbhall88/pistis/tree/v0.2.1). This drastically reduces the plot size and load time.
